package org.terraFutura;

import java.util.*;

/**
 * An effect that converts a fixed number of basic resources into a predefined set of outputs
 * and generates a fixed amount of pollution.
 */
public class ArbitraryBasic implements Effect {

    /** Required number of basic input resources. */
    private final int from;

    /** Exact list of output resources produced by this effect. */
    private final List<Resource> to;

    /** Amount of pollution cubes generated by this effect. */
    private final int pollution;

    /**
     * Creates a new arbitrary basic effect.
     *
     * @param from       required number of basic input resources (>= 0)
     * @param to         list of produced output resources (null = empty)
     * @param pollution  number of pollution cubes generated (>= 0)
     * @throws IllegalArgumentException if from < 0 or pollution < 0
     */
    public ArbitraryBasic(int from, List<Resource> to, int pollution) {
        if (from < 0) {
            throw new IllegalArgumentException("from must be >= 0");
        }
        if (pollution < 0) {
            throw new IllegalArgumentException("pollution must be >= 0");
        }
        this.from = from;
        this.pollution = pollution;
        this.to = to == null ? Collections.emptyList() : new ArrayList<>(to);
    }

    /**
     * Validates if this effect can be executed with the given input/output/pollution values.
     * Input must consist of exactly {@code from} basic resources.
     * Output must match {@code to} as a multiset.
     * Pollution must match the configured pollution amount.
     *
     * @return true if all conditions are met
     */
    @Override
    public boolean check(List<Resource> input, List<Resource> output, int pollution) {
        if (pollution != this.pollution) return false;
        if (!sameMultiset(output, to)) return false;

        if (input == null || input.size() != from) return false;
        for (Resource r : input) {
            if (!isBasic(r)) return false;
        }
        return true;
    }

    /**
     * Returns whether the given resource counts as a basic resource.
     */
    private boolean isBasic(Resource r) {
        return r == Resource.Green
                || r == Resource.Red
                || r == Resource.Yellow;
    }

    /**
     * Checks if two lists contain exactly the same multiset of resources
     * (order does not matter, counts must match).
     */
    private boolean sameMultiset(List<Resource> a, List<Resource> b) {
        if (a == null) a = Collections.emptyList();
        if (b == null) b = Collections.emptyList();

        if (a.size() != b.size()) return false;

        Map<Resource, Integer> counts = new EnumMap<>(Resource.class);
        for (Resource r : a) {
            counts.put(r, counts.getOrDefault(r, 0) + 1);
        }
        for (Resource r : b) {
            Integer c = counts.get(r);
            if (c == null || c == 0) return false;
            counts.put(r, c - 1);
        }
        return true;
    }

    /**
     * This effect never grants assistance.
     */
    @Override
    public boolean hasAssistance() {
        return false;
    }

    /**
     * Returns a simple textual representation of the effect.
     */
    @Override
    public String state() {
        return "ArbitraryBasic{" +
                "from=" + from +
                ", to=" + to +
                ", pollution=" + pollution +
                '}';
    }
}