package org.terraFutura;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.*;

/**
 * TransformationFixed represents a fixed transformation effect defined by:
 *  -a fixed list of input resources ("from")
 *  -a fixed list of output resources ("to")
 *  -a fixed pollution value
 * This effect succeeds only if the transformation performed by the player
 * exactly matches the defined input/output lists and pollution.
 */
public class TransformationFixed implements Effect {

    /** Fixed input resource list required for this effect */
    private final List<Resource> from;

    /** Fixed output resource list produced by this effect */
    private final List<Resource> to;

    /** Fixed pollution value associated with this effect */
    private final int pollution;

    /**
     * Creates a fixed transformation effect.
     *
     * @param from      required input resources
     * @param to        output resources produced
     * @param pollution pollution generated by this effect
     */
    public TransformationFixed(List<Resource> from, List<Resource> to, int pollution) {
        this.from = new ArrayList<>(from);
        this.to = new ArrayList<>(to);
        this.pollution = pollution;
    }

    /**
     * Checks whether a requested transformation matches this fixed effect exactly.
     *
     * @param input     resources the player paid
     * @param output    resources the effect produced
     * @param pollution pollution produced by the action
     * @return true if the transformation matches this effect's definition
     */
    @Override
    public boolean check(List<Resource> input, List<Resource> output, int pollution) {
        if(pollution != this.pollution) return false;
        if(!sameMultiset(input,from)) return false;
        if(!sameMultiset(output,to)) return false;
        return true;
    }

    /**
     * Checks if two lists contain exactly the same multiset of resources
     * (order does not matter, counts must match).
     */
    private boolean sameMultiset(List<Resource> a, List<Resource> b) {
        if (a == null) a = Collections.emptyList();
        if (b == null) b = Collections.emptyList();

        if (a.size() != b.size()) return false;

        Map<Resource, Integer> counts = new EnumMap<>(Resource.class);
        for (Resource r : a) {
            counts.put(r, counts.getOrDefault(r, 0) + 1);
        }
        for (Resource r : b) {
            Integer c = counts.get(r);
            if (c == null || c == 0) return false;
            counts.put(r, c - 1);
        }
        return true;
    }
    
    /**
     * Simplified rules: no Assistance effects are supported in this project.
     *
     * @return always false
     */
    @Override
    public boolean hasAssistance() {
        return false;
    }

    /**
     * Produces a JSON representation of this effect.
     *
     * @return JSON string containing "from", "to", and "pollution"
     */
    @Override
    public String state() {
        JSONObject obj = new JSONObject();
        obj.put("from", new JSONArray(from));
        obj.put("to", new JSONArray(to));
        obj.put("pollution", pollution);
        return obj.toString();
    }
}


